name: CI

on:
  # push:
  #   branches:
  #     - master
  #   tags:
  #     - v[0-9]+.[0-9]+.[0-9]+*
  # pull_request:

  # manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
    steps:
      - name: Fix git checkout line endings
        run: git config --global core.autocrlf input
      - uses: actions/checkout@v2.4.0
      - name: Use Node.js 17.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 17.x
          cache: yarn
      - name: Install latest NPM on Windows
        if: matrix.os == 'windows-latest'
        # See https://github.com/actions/virtual-environments/issues/4856#issuecomment-1043256330
        # and https://github.com/actions/setup-node/issues/411#issuecomment-1051084491
        run: |
          npm install -g npm@8.3.1
          npm install -g npm@latest
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Zip
        uses: papeloto/action-zip@v1
        with:
          files: packages/electron/out
          dest: build.zip
      - name: Upload zip
        uses: actions/upload-artifact@v3
        with:
          name: onlybuys-bot-${{ matrix.os }}-v0.0.${{ github.run_number }}
          path: build.zip
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.0.${{ github.run_number }}
          release_name: Release v0.0.${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Download Windows release asset
        id: download-windows-asset
        uses: actions/download-artifact@v3
        with:
          name: onlybuys-bot-windows-latest-v0.0.${{ github.run_number }}
          path: ./onlybuys-bot-windows-latest-v0.0.${{ github.run_number }}
      - name: Windows download path
        run: echo ${{ steps.download-windows-asset.outputs.download-path }}
      - name: Download MacOS release asset
        id: download-macos-asset
        uses: actions/download-artifact@v3
        with:
          name: onlybuys-bot-macOS-latest-v0.0.${{ github.run_number }}
          path: ./onlybuys-bot-macOS-latest-v0.0.${{ github.run_number }}
      - name: MacOS download path
        run: echo ${{ steps.download-macos-asset.outputs.download-path }}
      - name: Download Ubuntu release asset
        id: download-ubuntu-asset
        uses: actions/download-artifact@v3
        with:
          name: onlybuys-bot-ubuntu-latest-v0.0.${{ github.run_number }}
          path: ./onlybuys-bot-ubuntu-latest-v0.0.${{ github.run_number }}
      - name: Ubuntu download path
        run: echo ${{ steps.download-ubuntu-asset.outputs.download-path }}
      - name: Working directory contents
        run: ls -R
      - name: Upload Windows Asset
        id: upload-windows-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./onlybuys-bot-windows-latest-v0.0.${{ github.run_number }}/build.zip
          asset_name: onlybuys-bot-win64-v0.0.${{ github.run_number }}.zip
          asset_content_type: application/zip
      - name: Upload MacOS Asset
        id: upload-macos-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./onlybuys-bot-macOS-latest-v0.0.${{ github.run_number }}/build.zip
          asset_name: onlybuys-bot-mac-x86-v0.0.${{ github.run_number }}.zip
          asset_content_type: application/zip
      - name: Upload Ubuntu Asset
        id: upload-ubuntu-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./onlybuys-bot-ubuntu-latest-v0.0.${{ github.run_number }}/build.zip
          asset_name: onlybuys-bot-ubuntu-v0.0.${{ github.run_number }}.zip
          asset_content_type: application/zip
