name: Publish

on:
  # push:
  #   branches:
  #     - master
  #   tags:
  #     - v[0-9]+.[0-9]+.[0-9]+*
  # pull_request:

  # manual trigger
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 17.x
          cache: yarn
      - name: install dependencies
        run: yarn install
      - name: Bundle CLI
        run: yarn workspace @onlybuys-bot/cli bundle
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd packages/electron && yarn publish
